#require_relative "./lib/Artistservice"
# require "rest-client"
# require "json"
#require 'pry'
#class API
# 
#“Efua” => “3bjAdDLHWwdkMsBBNaxXx6”,  
#   curl -X "GET" "https://api.spotify.com/v1/artists/3bjAdDLHWwdkMsBBNaxXx6/albums?include_groups=single&market=ES&limit=5&offset=0" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQAv0pDc_-K4I01-dqMtzskn0TdzSZHsuu21AAyDnwJbrxlbvBOsehvGjVtOftJ9w48a1XUq4Viq5TSBjZ8Jc5LLhA7iakCt-BCnpt6aGXCrFwVQWNaWObNAqTLOE7e1QgPeNwzueQ"

#“Adele” => “4dpARuHxo51G3z768sgnrY”, 
#curl -X "GET" "https://api.spotify.com/v1/artists/4dpARuHxo51G3z768sgnrY/albums?include_groups=single&market=ES&limit=5&offset=0" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQAv0pDc_-K4I01-dqMtzskn0TdzSZHsuu21AAyDnwJbrxlbvBOsehvGjVtOftJ9w48a1XUq4Viq5TSBjZ8Jc5LLhA7iakCt-BCnpt6aGXCrFwVQWNaWObNAqTLOE7e1QgPeNwzueQ"


#“Beyonce” => "6vWDO969PvNqNYHIOW5v0m” ,
#https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m/albums?include_groups=single&market=ES&limit=5&offset=0

#“Alicia Keys” => “3DiDSECUqqY1AuBP8qtaIa” , 
# curl -X "GET" "https://api.spotify.com/v1/artists/3DiDSECUqqY1AuBP8qtaIa/albums?include_groups=single&market=ES&limit=5&offset=0" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQAv0pDc_-K4I01-dqMtzskn0TdzSZHsuu21AAyDnwJbrxlbvBOsehvGjVtOftJ9w48a1XUq4Viq5TSBjZ8Jc5LLhA7iakCt-BCnpt6aGXCrFwVQWNaWObNAqTLOE7e1QgPeNwzueQ"

#“Whitney Houston” => “ 6XpaIBNiVzIetEPCWDvAFP” 
#curl -X "GET" "https://api.spotify.com/v1/artists/6XpaIBNiVzIetEPCWDvAFP/albums?include_groups=single&market=ES&limit=5&offset=0" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQAv0pDc_-K4I01-dqMtzskn0TdzSZHsuu21AAyDnwJbrxlbvBOsehvGjVtOftJ9w48a1XUq4Viq5TSBjZ8Jc5LLhA7iakCt-BCnpt6aGXCrFwVQWNaWObNAqTLOE7e1QgPeNwzueQ"
#
#end 
#Artist_hash = JSON.parse{resp.body, symbolize_names:true}
#response = RestClient.get 'https://api.spotify.com/v1/artists/3bjAdDLHWwdkMsBBNaxXx6/albums?include_groups=single&market=ES&limit=5&offset=0" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQBNEr6gFsX2559ebhjGpBLOFrBIzLRggWo1BWa4HpAQhzZs-axZRYjvnLhz2jYYwWyle9M1aEYN-PUuLjxKQ9PH
#binding.pry